### ISSUE TITLE
Epic 2: People want to see their progress but lack tools to visualize their improvement.

### ISSUE THREAD

**Issue by isabellegoralsky** [isabellegoralsky/cs130-project#2]
## Epic
People want to see their progress but lack the tools to visualize their improvement.

## User Stories
- [x] #35
- [x] #34

## Use Cases and Features
- [x] Users should be able to view their personal goals and achievements on their profile.
- [x] Users should be able to update and track their PRs (personal records).
- [x] Users should be able to create specific goals for themselves.
